spring:
  data:
    cassandra:
      keyspace-name: main
      username: TfySwvbeUbseeLpeGZJIMpDI
      password: <secret>
      schema-action: create_if_not_exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10

datastax.astra:
  secure-connect-bundle: secure-connect.zip

astra.db:
    id: <db-id>
    region: europe-west1
    keyspace: main
    application.token: <token>